resource "aws_vpc" "main" {}
resource "aws_route_table" "main" {}
resource "aws_security_group" "base" {}
resource "aws_subnet" "subnet_1" {}
resource "aws_subnet" "subnet_2" {}
resource "aws_subnet" "subnet_3" {}
resource "aws_route_table_association" "rt_association_1" {}
resource "aws_route_table_association" "rt_association_2" {}
resource "aws_route_table_association" "rt_association_3" {}
resource "aws_vpc_endpoint" "ec2" {}
resource "aws_vpc_endpoint" "ec2messages" {}
resource "aws_vpc_endpoint" "s3" {}
resource "aws_vpc_endpoint" "ssm" {}
resource "aws_flow_log" "main" {}
resource "aws_vpc_dhcp_options" "main" {}
resource "aws_vpc_dhcp_options_association" "main" {}
resource "aws_security_group_rule" "base_ingress_v4" {}
resource "aws_security_group_rule" "base_egress" {}
resource "aws_ec2_transit_gateway_vpc_attachment" "main" {}
resource "aws_route53_resolver_rule_association" "mskcc_tld" {}
resource "aws_route53_resolver_rule_association" "cross_vpc" {}
resource "aws_default_network_acl" "main" {}
resource "aws_route53_resolver_rule_association" "internet" {}
resource "aws_route" "main" {}
resource "aws_ec2_transit_gateway_route" "main" {}
resource "aws_ec2_transit_gateway_route_table_association" "main" {}
resource "aws_ec2_transit_gateway_route_table_propagation" "main" {}
resource "aws_ec2_transit_gateway_route_table_propagation" "msk" {}
resource "aws_ram_resource_share" "vpc" {}